logo: /assets/images/logo.png
title: "HR & Legal school"
locale: ru-RU
description: "Курсы повышения квалификации для юристов и кадровиков. Высшая Школа Юриста и Кадрового Администрирования «HR & Legal school»."
url: "https://hrlegalschool.kz"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

markdown: kramdown
kramdown:
  input: GFM

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"

# Enable search
search:
  enabled: true
atom_feed:
  hide: true

footer:
  links:
    - label: "WhatsApp"
      icon: "fab fa-whatsapp"
      url: "https://wa.me/77071210321"
    - label: "Telegram"
      icon: "fab fa-telegram"
      url: "https://t.me/yourprofile"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/yourprofile"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://facebook.com/yourprofile"

  copyright:
    text: "© 2025 HR & Legal school. Все права защищены."

