logo: /assets/images/logo.png
title: "SK&Begimbet"
locale: ru-RU
description: "Курсы повышения квалификации для юристов и кадровиков. Высшая Школа Юриста и Кадрового Администрирования «SK&Begimbet»."
url: "https://mdrmv.github.io/sk-begimbet"
baseurl: "/sk-begimbet"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

markdown: kramdown
kramdown:
  input: GFM

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"

# Enable search
search:
  enabled: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

footer:
  links:
    - label: "WhatsApp"
      icon: "fab fa-whatsapp"
      url: "https://wa.me/77071210321"
    - label: "Telegram"
      icon: "fab fa-telegram"
      url: "https://t.me/yourprofile"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/yourprofile"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://facebook.com/yourprofile"

  copyright:
    text: "© 2025 Высшая Школа Юриста и Кадрового Администрирования «SK&Begimbet». Все права защищены."
